# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 956bc241dc47f0106fe8a777b765b05e6bb49928c78b39bfd8631f82327967a9690c82ad5020d42b6766e0db8788d6ad966a6f12c0f25227059da9536d0e8376

test:
  secret_key_base: 77c0a40704134bbdf6f5499d51f742ab9f7f6b21b8abf823708b53827c770d09d22dd317668e3665bcbddf95123348f6ff5e490589c79b0cff67382ff58f464a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
